const db = require('../db/connection');

async function getDivisionTypes(req,res,next){try{const [rows]=await db.execute(`SELECT dt.*,w.name created_by_name,
  (SELECT COUNT(*) FROM panel_divisions pd WHERE pd.division_type=dt.name) usage_count
  FROM division_types dt LEFT JOIN workers w ON w.id=dt.created_by
  ${req.query.include_inactive==='true'&&['owner','head_engineer'].includes(req.worker.role)?'':'WHERE dt.is_active=1'}
  ORDER BY dt.sort_order,dt.name`);res.json(rows);}catch(e){next(e)}}

async function createDivisionType(req,res,next){try{const name=String(req.body.name||'').trim();const color=String(req.body.color||'#64748b').trim();if(!name||name.length>100)return res.status(400).json({error:'Division name is required and must be 100 characters or less'});if(!/^#[0-9a-f]{6}$/i.test(color))return res.status(400).json({error:'Choose a valid color'});const [[order]]=await db.execute('SELECT COALESCE(MAX(sort_order),0)+1 n FROM division_types');const [result]=await db.execute('INSERT INTO division_types(name,color,sort_order,created_by) VALUES(?,?,?,?)',[name,color,order.n,req.worker.id]);const [[row]]=await db.execute('SELECT * FROM division_types WHERE id=?',[result.insertId]);res.status(201).json(row);}catch(e){if(e.code==='ER_DUP_ENTRY')return res.status(409).json({error:'This division type already exists'});next(e)}}

async function updateDivisionType(req,res,next){try{const [[old]]=await db.execute('SELECT * FROM division_types WHERE id=?',[req.params.id]);if(!old)return res.status(404).json({error:'Division type not found'});const name=String(req.body.name??old.name).trim();const color=String(req.body.color??old.color).trim();const active=req.body.is_active===undefined?old.is_active:(req.body.is_active?1:0);if(!name||name.length>100)return res.status(400).json({error:'Invalid division name'});if(!/^#[0-9a-f]{6}$/i.test(color))return res.status(400).json({error:'Choose a valid color'});const conn=await db.getConnection();try{await conn.beginTransaction();await conn.execute('UPDATE division_types SET name=?,color=?,is_active=? WHERE id=?',[name,color,active,req.params.id]);if(name!==old.name)await conn.execute('UPDATE panel_divisions SET division_type=? WHERE division_type=?',[name,old.name]);await conn.commit();}catch(e){await conn.rollback();throw e}finally{conn.release()}const [[row]]=await db.execute('SELECT * FROM division_types WHERE id=?',[req.params.id]);res.json(row);}catch(e){if(e.code==='ER_DUP_ENTRY')return res.status(409).json({error:'This division type already exists'});next(e)}}

async function deleteDivisionType(req,res,next){try{const [[type]]=await db.execute('SELECT * FROM division_types WHERE id=?',[req.params.id]);if(!type)return res.status(404).json({error:'Division type not found'});const [[used]]=await db.execute('SELECT COUNT(*) n FROM panel_divisions WHERE division_type=?',[type.name]);if(Number(used.n)){await db.execute('UPDATE division_types SET is_active=0 WHERE id=?',[req.params.id]);return res.json({message:'Division type is in use, so it was archived instead of deleted',archived:true});}await db.execute('DELETE FROM division_types WHERE id=?',[req.params.id]);res.json({message:'Division type deleted'});}catch(e){next(e)}}

module.exports={getDivisionTypes,createDivisionType,updateDivisionType,deleteDivisionType};
