import { useEffect,useState } from 'react';
import toast from 'react-hot-toast';
import api from '../api/client';

export default function ProcurementPage() {
  const [projects,setProjects]=useState([]),[loading,setLoading]=useState(true),[notes,setNotes]=useState({}),[saving,setSaving]=useState(null),[receiving,setReceiving]=useState(null),[receiveQty,setReceiveQty]=useState({});
  const load=()=>{setLoading(true);api.get('/procurement/projects').then(r=>setProjects(r.data)).catch(e=>toast.error(e.message)).finally(()=>setLoading(false));};
  useEffect(load,[]);
  const review=async(project,action)=>{setSaving(project.id);try{await api.patch(`/procurement/projects/${project.id}/review`,{action,note:notes[project.id]||null});toast.success(`Procurement ${action==='approve'?'approved':'rejected'}`);load();}catch(e){toast.error(e.response?.data?.error||e.message);}finally{setSaving(null);}};
  const receive=async(project,item)=>{const key=`${project.id}-${item.product_id}`,quantity=parseInt(receiveQty[key]);if(!quantity||quantity<1){toast.error('Enter the quantity allocated to this project');return;}setReceiving(key);try{await api.patch(`/procurement/projects/${project.id}/products/${item.product_id}/receive`,{quantity});toast.success(`Allocated ${quantity} of ${item.item_name} to this project (stock unchanged)`);setReceiveQty(q=>({...q,[key]:''}));load();}catch(e){toast.error(e.response?.data?.error||e.message);}finally{setReceiving(null);}};
  return <div className="page">
    <div className="page-header"><div><div className="page-title">📦 Procurement Queue</div><div className="page-subtitle">Stock Manager, Owner, or Head Engineer approval is required before Assembly</div></div><button className="btn btn-secondary" onClick={load}>↻ Refresh</button></div>
    {loading?<div style={{textAlign:'center',padding:40}}><span className="spinner"/></div>:!projects.length?<div className="empty"><div className="empty-icon">✅</div><p>No projects waiting in Procurement.</p></div>:
      <div style={{display:'grid',gap:16}}>{projects.map(project=><section className="card" key={project.id} style={{overflow:'hidden'}}>
        <div className="card-body"><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',marginBottom:12}}><div><h3 style={{margin:0}}>{project.project_name}</h3><small style={{color:'var(--muted)'}}>{project.quote_number||`Project #${project.id}`} · Engineer: {project.engineer_name||'Unassigned'}</small></div><span className={`badge ${project.procurement_status==='approved'?'badge-green':project.procurement_status==='rejected'?'badge-red':'badge-yellow'}`}>{project.procurement_status}</span></div>
        <div className="table-wrap"><table><thead><tr><th>Item</th><th>Description</th><th>Required</th><th>Stock</th><th>Reserved</th><th>Project Allocation</th><th>Available for Project</th><th>Quick Add Allocation</th><th>Shortage</th></tr></thead><tbody>
          {project.items.map((item,index)=>{const key=`${project.id}-${item.product_id}`;return <tr key={`${item.product_id||'manual'}-${index}`}><td className="mono">{item.item_name}</td><td>{item.description||'—'}</td><td className="mono">{item.required_qty}</td><td className="mono">{item.stock_qty}</td><td className="mono">{item.reserved_qty}</td><td className="mono" style={{color:item.allocated_qty?'var(--accent2)':'var(--muted)'}}>{item.allocated_qty}</td><td className="mono" style={{fontWeight:700}}>{item.available_for_project}</td><td>{item.product_id?<div style={{display:'flex',gap:5,minWidth:150}}><input type="number" min="1" step="1" className="form-input" style={{width:72,padding:'4px 6px'}} placeholder={item.shortage_qty?String(item.shortage_qty):'Qty'} value={receiveQty[key]||''} onChange={e=>setReceiveQty(q=>({...q,[key]:e.target.value}))}/><button className="btn btn-sm btn-secondary" disabled={receiving===key} onClick={()=>receive(project,item)}>{receiving===key?'...':'+ Add'}</button></div>:<span style={{color:'var(--muted)'}}>Manual item</span>}</td><td className="mono" style={{color:item.shortage_qty?'var(--danger)':'var(--success)',fontWeight:700}}>{item.shortage_qty||'✓'}</td></tr>})}
          {!project.items.length&&<tr><td colSpan="9">No CRM items in this project.</td></tr>}
        </tbody></table></div>
        <div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap',marginTop:12}}><input className="form-input" style={{flex:'1 1 260px'}} placeholder="Review note (required when rejecting)" value={notes[project.id]||''} onChange={e=>setNotes(n=>({...n,[project.id]:e.target.value}))}/><button className="btn btn-danger" disabled={saving===project.id||!notes[project.id]?.trim()} onClick={()=>review(project,'reject')}>Reject</button><button className="btn btn-primary" disabled={saving===project.id||project.shortage_count>0||!project.items.length} onClick={()=>review(project,'approve')}>{project.shortage_count?`${project.shortage_count} shortage(s)`:'Approve Stock →'}</button></div>
        </div></section>)}</div>}
  </div>;
}
