const { ROLE_PERMISSIONS, MANAGEMENT_ROLES } = require('./rolePolicy');

// Curated guidance only: no SQL, external requests, model tools, or record mutations.
const topics = [
  { id:'projects', title:'Projects and quotations', permission:'projects', path:'/projects', words:['project','quotation','quote','panel','division','item','crm','pdf','export'], text:'Open Projects, select a project you are authorized to access, then open its CRM. Organize panels, divisions and items; check quantities and technical details before exporting. Review the quotation version before sharing it with the client.', engineer:'Work on your assigned projects. Confidential prices remain hidden; use the available markup and discount controls and authorized exports.' },
  { id:'workflow', title:'Stages and approvals', permission:'projects', path:'/projects', words:['stage','workflow','approval','approve','revision','recheck','cancel','design','delivery','delivered'], text:'Projects move through Design → Quotation → Approval → Procurement → Assembly → Testing → Delivered. Open the project CRM to review approval status and review history.', engineer:'Finish your panels and items, then use Submit for approval. Wait for owner or head engineer approval before moving to Quotation. For recheck, read the notes in CRM or email, make the requested edits and submit again. A cancelled project cannot be edited. Confidential prices remain hidden.', management:'Open Management review in the project CRM to approve submitted work, request recheck with notes, or cancel with notes. The engineer receives the decision and notes in CRM and email. Review assignments and stage history before advancing later stages.' },
  { id:'products', title:'Products and stock', permission:'products', path:'/products', words:['product','stock','inventory','warehouse','brand','catalog','quantity'], text:'Open Products and search by reference or description. Check actual warehouse stock against demand before promising material. Only authorized roles can change inventory; a project allocation does not increase warehouse stock.' },
  { id:'reservations', title:'Demand and shortages', permission:'reservations', path:'/reservations', words:['demand','reservation','reserve','shortage','required','material'], text:'Open Demand Tracker to compare required material with available stock and reservations. Demand reflects panel quantities and excludes fulfilled demand. Check existing allocations to avoid committing the same material twice.' },
  { id:'procurement', title:'Procurement and allocation', permission:'procurement', path:'/procurement', words:['procurement','allocate','allocation','purchase','supplier','available'], text:'Open Procurement Queue, review required quantities and shortages, then use the controls available to your role. Available for Project is a project-only allocation; it does not add warehouse inventory. Review stock and reservations before allocating.', management:'Review procurement readiness and approve only after checking that required material is available.' },
  { id:'execution', title:'Execution and testing', permission:'execution', path:'/my-projects', words:['execution','task','complete','completion','testing','technician','assigned','progress'], text:'Open My Projects and select your assigned project. Mark only work that is actually complete and record testing details for engineer review. Progress is calculated from completed tasks; confirm every required task before reporting completion.' },
  { id:'clients', title:'Client records', permission:'clients', path:'/clients', words:['client','customer','contact'], text:'Open Clients, search for an existing record before creating another, and verify contact details. Use only the edit controls available to your role.' },
  { id:'debt', title:'Payments and reminders', permission:'debt', path:'/debt', words:['debt','payment','balance','invoice','financial','money','paid','reminder','remind'], text:'Open Debt to review outstanding balances, then open the project CRM Payments tab for payment history. When recording a partial payment, set the expected date for the remaining balance to receive an automatic overdue reminder. Verify the amount and date before saving. Ask “Show outstanding balances” for a live summary. I can guide you, but cannot record payments or send reminders from chat.' },
  { id:'analytics', title:'Business analytics', permission:'analytics', path:'/analytics', words:['analytics','revenue','profit','performance','statistics'], text:'Open Analytics to review business summaries, engineer performance and client statistics. Check filters and the reporting period before comparing totals or exporting.' },
  { id:'workers', title:'Team administration', permission:'workers', path:'/workers', words:['worker','user','team','role','account','password'], text:'Open Workers to manage team accounts and roles. Give each person only the access needed for their work. Never share passwords in chat.', management:'The head engineer can manage workers, but only the owner can delete users.' },
  { id:'upload', title:'Import Excel', permission:'upload', path:'/upload', words:['import','excel','upload','spreadsheet'], text:'Open Import Excel. Check references, brands and quantities in your file before uploading; review the import results for errors and verify affected products afterward.' },
  { id:'discounts', title:'Brand discounts', permission:'discounts', path:'/discounts', words:['discount','pricing','price','cost','markup'], text:'Open Brand Discounts to review authorized discount settings. Check the brand and percentage before saving, then review the affected quotation using authorized financial views.' },
  { id:'requests', title:'Engineer collaboration requests', permission:'requests', path:'/requests', words:['collaboration','collaborate','cooperate','cooperation','cop','invitation','invite','blocker'], text:'Open the project details to request collaboration with another engineer. Select the engineer and explain the help needed. Open Requests to review Incoming invitations and Sent requests. The invited engineer can accept or reject; rejection requires a reason. You can revoke a sent request. Access to the shared project begins after acceptance.' },
  { id:'groups', title:'Item group templates', permission:'item-groups', path:'/groups', words:['group','template'], text:'Open Item Groups to review reusable item templates. Check their contents and quantities before adding them to a project division.' },
  { id:'messages', title:'Announcements', permission:'messages', path:'/messages', words:['announcement','message','communication'], text:'Open Announcements to read team updates. If your role has posting controls, include clear project context and the action needed.' },
  { id:'calendar', title:'Deadlines and calendar', roles:['owner','head_engineer','engineer','accounting','secretary'], path:'/calendar', words:['calendar','deadline','schedule','overdue'], text:'Open Calendar to review project deadlines. Open the relevant project to check its status and coordinate a realistic delivery date with the responsible engineer.' },
  { id:'divisions', title:'Division types', roles:MANAGEMENT_ROLES, path:'/division-types', words:['division type'], text:'Open Division Types to manage the available project division categories. Review existing usage before changing a type.' },
  { id:'notifications', title:'Notifications', roles:['owner','head_engineer','engineer','accounting','secretary','stock_manager'], path:'/notifications', words:['notification','alert'], text:'Open Notifications to review alerts. Check the linked record and resolve the underlying issue before marking an alert as read.' },
  { id:'updates', title:'What’s New', roles:Object.keys(ROLE_PERMISSIONS), path:'/updates', words:['update','new','help'], text:'Open What’s New to review application changes. You can also use Help & Tutorial for a walkthrough of your role.' },
];

function allowedTopics(role) {
  const permissions = ROLE_PERMISSIONS[role] || [];
  return topics.filter(t => t.permission ? permissions.includes(t.permission) || (t.id === 'execution' && MANAGEMENT_ROLES.includes(role)) : t.roles.includes(role))
    .map(t => t.id === 'execution' && MANAGEMENT_ROLES.includes(role) ? { ...t, path:'/projects', text:'Open Projects to coordinate execution, assign technicians and review completion and testing. Technicians use My Projects for assigned work. Verify actual task completion and testing results before delivery.' } : t);
}
const link = t => ({ label:t.title, path:t.path, topic:t.id });
function roleOverview(worker, allowed) {
  const summaries = {
    owner: 'Review approval requests, approve work, request recheck or cancel with notes; coordinate engineer collaboration; review payments and overdue reminders; manage stock, procurement and team accounts.',
    head_engineer: 'Review approval requests, approve work, request recheck or cancel with notes; coordinate engineer collaboration, procurement, execution and testing; review payments and reminders. Owner accounts remain protected.',
    engineer: 'Manage your assigned projects and panels, submit work for approval, read recheck notes and resubmit; request collaboration with another engineer and accept or reject invitations. Wait for management approval before Quotation. Prices and payment tools remain private.',
    accounting: 'Review authorized project prices, record payments, set the expected date for a remaining balance, review overdue reminders and outstanding debts, and manage client records.',
    stock_manager: 'Review products, warehouse stock, demand and shortages; use authorized procurement and allocation controls and review stock alerts.',
    secretary: 'Maintain client contact records, review products and material demand, read or post authorized announcements, and check deadlines and notifications.',
    technician: 'Open your assigned work in My Projects, update actual task completion and record testing details for engineer review.',
  };
  return { reply:`As ${worker.role.replaceAll('_',' ')}, your available actions are:\n\n${summaries[worker.role]}\n\nChoose a tool below for its steps, or ask “What do I have today?” for your live records.`, topic:'role', links:allowed.map(link), suggestions:[{ label:'What do I have today?' }, ...allowed.filter(t => ['workflow','requests','debt','procurement','execution'].includes(t.id)).map(link)] };
}
function answer(worker, message, previousTopic) {
  const allowed = allowedTopics(worker.role);
  if (!allowed.length) return { reply:'Your role is not recognized. Please contact the owner to check your access.', suggestions:[], links:[] };
  const text = message.toLowerCase().normalize('NFKC');
  if (/\b(ignore .*instructions|system prompt|bypass|sql|token|secret|hack)\b/.test(text)) return { reply:'I can explain authorized workflows, but cannot reveal credentials, bypass permissions, or execute commands. Choose a task below.', suggestions:allowed.slice(0,4).map(link), links:[] };
  const casual = text.trim().replace(/[!?.]+/g, '').replace(/\s+/g, ' ');
  let smallTalk;
  if (/^(?:(?:hey|hi|hello)[, ]+)?(?:how are you|how are u|how r u|how's it going|how is it going|and you|what about you)$/.test(casual)) smallTalk = "I'm doing well, thank you! How are you? Ready to get started? Would you like to see what needs your attention today?";
  else if (/^(?:i'?m |i am |doing )?(?:good|fine|great|well|okay|ok)(?: thanks| thank you)?(?: and you)?$/.test(casual)) smallTalk = "Glad to hear it! Let's get to work. Would you like your projects, requests and other items that need attention today?";
  else if (/^(thanks|thank you|thank u|thx|thank you so much)$/.test(casual)) smallTalk = "You're welcome! Would you like to check what needs your attention today?";
  else if (/^(bye|goodbye|see you|see you later)$/.test(casual)) return { reply:'See you later! Your work will be here when you return.', topic:previousTopic, links:[], suggestions:[{label:'What do I have today?'}] };
  else if (/^(?:i'?m |i am )?(tired|stressed|busy|not good)$/.test(casual)) smallTalk = "Let's take it one step at a time. Would you like to start with the work that needs your attention today?";
  if (smallTalk) return {reply:smallTalk,topic:'conversation:daily',links:[],suggestions:[{label:'Yes, show my work today'},{label:'My role and tools'}]};
  if (/\b(what can (i|you) do|my role|my tools|my permissions|available actions|what.*(access|role.*has))\b/.test(text)) return roleOverview(worker, allowed);
  if (/^(hi|hello|hey|help|good morning|good afternoon|good evening)[!?.\s]*$/.test(text)) return { reply:`Hello ${worker.name}, how can I help you today? Let's get to work. Would you like to see what needs your attention today? I can also explain your role's tools.`, topic:'conversation:daily', suggestions:[{ label:'What do I have today?' }, { label:'My role and tools' }, ...allowed.slice(0,3).map(link)], links:[] };
  const words = text.match(/[a-z]+/g) || [];
  const score = t => t.words.reduce((n, w) => n + ((w.includes(' ') ? text.includes(w) : words.includes(w) || words.includes(w+'s')) ? 1 : 0), 0);
  const ranked = topics.map(t => ({ topic:t, score:score(t) })).filter(t => t.score > 0).sort((a,b) => b.score-a.score);
  let topic = /\b(requests?|help)\b.*\b(eng|engineer)\b/.test(text) ? topics.find(t => t.id === 'requests') : ranked[0]?.topic;
  if (!topic && /\b(next|more|how|steps|explain|that|it)\b/.test(text)) {
    const context = {'records:approvals':'workflow','records:requests':'requests','records:debt':'debt','records:stock':'reservations','records:projects':worker.role==='technician' ? 'execution' : 'projects','records:clients':'clients','records:daily':worker.role==='technician' ? 'execution' : worker.role==='accounting' ? 'debt' : worker.role==='stock_manager' ? 'procurement' : worker.role==='secretary' ? 'clients' : 'workflow'};
    topic = allowed.find(t => t.id === (context[previousTopic] || previousTopic));
  }
  if (topic && !allowed.some(t => t.id === topic.id)) return { reply:'That section is outside your role’s access. Ask the owner or head engineer for assistance. I can help with your authorized tools below.', links:[], suggestions:allowed.slice(0,4).map(link) };
  if (topic) topic = allowed.find(t => t.id === topic.id);
  if (!topic) return { reply:'Could you tell me which task you need help with? Ask “What do I have today?”, “Show my projects”, or search by a quoted name, such as find project "Office". I can read authorized records and explain application workflows.', links:[], suggestions:[{ label:'What do I have today?' }, ...allowed.slice(0,4).map(link)] };
  return { reply:[topic.text, worker.role === 'engineer' && topic.engineer, MANAGEMENT_ROLES.includes(worker.role) && topic.management].filter(Boolean).join('\n\n'), topic:topic.id, links:[link(topic)], suggestions:allowed.filter(t => t.id !== topic.id).slice(0,4).map(link) };
}
module.exports = { answer, allowedTopics };
